### PR TITLE
Add src-path option to run command

### PR DESCRIPTION
**Pull request by jdewit**
Bug fix: no
Feature addition: yes
Backwards compatibility break: no
tests pass: yes
Fixes the following issues: #67

This PR adds a src-path option to the run console command to give the ability to generate classes in a location other than "src".

### CODE REVIEW

**Comment by henrikbjorn** [comment]
maybe just `src` which is more concise and easier to remember.

**Comment by jdewit** [comment]
Yeah, I was just following the format as in the desc command.

It would be even better if this was configurable.

**Comment by umpirsky** [comment]
+1 to have this merged, it would be useful for Symfony bundles where `.` for `src-path` will probably work.

**Comment by umpirsky** [comment]
Any chance to get this option in 2.0? Its really useful for Symfony bundles.

**Comment by ghost** [comment]
@umpirsky : shouldn't this be submitted to phpspec/phpspec and not here?

**Comment by umpirsky** [comment]
Probably, I just wanted to bring it up.

**Pull request merged**
