### PR TITLE
Be a good citizen and add the visibility as stated in PSR

### PR DESCRIPTION
**Pull request by henrikbjorn**

### CODE REVIEW

**Comment by MarcelloDuarte** [comment]
@henrikbjorn I guess this is one of the places our frustration with PHP syntax comes out. We wish to build our tool to work as a domain specific language. We don't want what we don't need in the mist. If I could even the "function" keyword wouldn't be there. These are not methods of our SUS, they are statements of behaviour we wish added to our SUS. I don't think PSR apply here, we are a citizen of another country. But I am listening... what others think?

**Comment by everzet** [comment]
We had quite a debate on namings with @MarcelloDuarte couple of months before.

Here's how we see conventions: conventions are here to introduce style compatibility across different libraries. But why those conventions choose specific styles over others? For example, why `camelCasingMethodNames`? Because method names should be short and clear, right? So, `superLongMethodNameWithCamelCase` becomes horribly unreadable. So horribly unreadable, that even method author starts to see it. Why prepending every method with visibility operator? Because we need to differentiate API accessibility in our objects. That's in my opinion, one of the major convention benefits - good practices enforcement.

Ok, but what about specs? Does example names should be short and clear too? No, they should remove any confusion and misunderstanding, so be explicit as much as possible. That's why we're not applying shortening-enforcement convention here, cuz aim is opposite. Does visibility of example is more important than example itself? No, it's not, whenever we're talking about object behavior and examples of it, we're talking about observable, **public** behaviour, so visibility operators are useless noise here.

Are convention bad? No, they are great. Code of phpspec2 follows PSR itself. Are conventions compatible with DSL? In syntax-explicit languages, like php - mostly no. You still could create DSL on top of conventions, but those conventions will limit lot of readability possibilities for you.

So we had choice here - either be conventional OR to be readable. And in our opinion, specs primary job is to be readable. But you still has full control of your codebase (`/src`) and that's exactly the place where conventions should be applied:
- `/src` - conventions. PSR0, PSR1, PSR2 or nothing (your choice, as usual)
- `/spec` - readability.

**Comment by henrikbjorn** [comment]
Still omitting the visibilty will implicit mark it as `public` just like `var` and is a thing there is only there for backwards compatibility. Hopefully they will fix that some day. Being explicit about the visibility is necessary.

I can see you want to be DSL but it is not "really" possible in PHP like it is in languages like Ruby and people doing PHP know this.

**Comment by everzet** [comment]
I know nothing about plans to make `public` visibility unoptional. The day php will start dropping BC stuff, php will become absolutely different language and i'll start dancing jiga. But i don't see it as the case for visible future. So we have what we have and it's silly to not use what language offers. When php will offer better language constructions for expressiveness - we'll use those. But now...

**Comment by l3l0** [comment]
Hello,

On the one hand PHPSpec is tool for PHP developers, and some time ago we (PHP devs) agreed on PSR stuff and it is quite great and helpful IMHO. I think that specification is code  too, so PSR-x should apply here. BTW that why underscore notation is confusing for me too. I understand that it can be more readable or something but camelCase is standard right now and I do not want to switch convention/work routine when I working with code.

On the other hand I understand @MarcelloDuarte point about DSL. It will be quite cool but I think that PHP is just quite bad with handling of such stuff...

just few my thoughts :)

PS

Really great tool/work guys :)

**Comment by everzet** [comment]
@l3l0 well, if you think that you can switch from your code to spec level automatically, without even thinking about it, you're wrong (IMO). Implementation and implementation description are just too different things with different goals. They solve different problems. One describes your system contracts, another fulfils those contracts. You need to differentiate those, you need to feel the difference. For me, the fact that tool forces you to switch mindset from code to spec is a feature.

**Comment by everzet** [comment]
BTW, it's really great that @henrikbjorn raised this topic now. We had this discussion for quite some time with Marcello. And it's good finally to bring conversation to community.

**Comment by MarcelloDuarte** [comment]
I can't agree with @everzet more. phpspec does follow PSR. Just look at phpspec code.

Specs are not code, they are erm... specs. We are using whatever is available in PHP today to make it readable. Language is more important than standards here. That's an important point about BDD. We happen to use methods in a class to represent our examples. Rspec doesn't do that. We are not really trying to repeat rspec DSL. The goal is offer a way to describe the objects and keep focus on what matters most.

I suppose this isn't a straight forward concept if you are coming from PHPUnit experience and has had none SpecBDD experience from another language before...

**Comment by everzet** [comment]
Just an example of what we all are talking about here (for side-readers:) ):

``` php
class StringPresenter extends ObjectBehavior
{
    function it_should_present_only_first_line_of_multiline_string()
    {
        $this->presentValue("some\nmultiline\nvalue")->shouldReturn('"some"...');
    }
```

VS

``` php
class StringPresenter extends ObjectBehavior
{
    public function itShouldPresentOnlyFirstLineOfMultilineString()
    {
        $this->presentValue("some\nmultiline\nvalue")->shouldReturn('"some"...');
    }
```

Just to read those two out loud (and really fast) and you'll see why we made decisions that we made :)

**Comment by henrikbjorn** [comment]
I am not talking about using camelCase instead of using underscores for method names. Just adding the `public` visibility keyword as it should be instead of relying on php implicitly doing it itself.

**Comment by everzet** [comment]
@henrikbjorn yeah, i got you. It was comment for both you and @l3l0 :)

But still, it's just part of "solution". This is fun thing about conventions. You can't be partly-conventional. You're either compatible or not. And adding `public` will not make specs PSR-compliant, though will surely make examples 1-step less readable. So i'm not evaluating "adding only `public` operator" as a real change, i'm evaluating either we're following PSR fully or not :) And currently i see no other cons for being PSR-incompatible except "i can't think anymore in code terms inside spec", which is a feature, in my opinion :)

**Comment by clemherreman** [comment]
@everzet summed it up, PSR conventions shouldn't apply here, as their aim is totally different. Only interoperability concerns should be used, like PSR-0.

@l3l0 also PSR-X isn't about PHP devs, but more about PHP frameworks using the same lingua franca. The aim is to make framework and libs interoperable. Such specifications shouldn't be followed religiously. By default you follow them, but leaves them as soon as it doesn't make sense/doesn't improve your project/lib.

**Comment by henrikbjorn** [comment]
@everzet the PSR in the commit is somewhat misleading. I think that the main issue is that the spec generated is relying on php's internal visibility magic instead of being explicit about it. Not having the public keyword is pre PHP 5.

**Comment by everzet** [comment]
@henrikbjorn got ya. Still, even unintentionally, you've raised very valid and interesting conversation :)

As of "this feature could break in the future" argument - i don't see this coming in any near future. There's just too many libs, that rely on it (most Symfony2 interfaces had no public keyword couple months before). And in comparison with most of those libs, our usage even has valid argument. Also, when and if this change will happen - we'll kindly give specers clean instructions or even tool to upgrade. But for now, this feature (optional `public`) is here and i don't see any end date to it. And as i've said - it would be stupid to not use tools or constructions, that language offers. Even if those tools were created/left with wrong/problematic intentions. We kinda limited in choices here, in php ;)

**Comment by l3l0** [comment]
I like to be wrong cause then I can learn something :) I am not saying about religiously follow standards and I always prefer to think before I write code. TDD and BDD helping me with that :) @everzet @MarcelloDuarte Thanks for clearing some stuff for me. I just thought that spec is code too. Same I treated unit test, so try to implement my tests in readable way using standard conventions which I use for production code. Funny is that for me second @everzet example is more readable... matter of habits probably.

Probably I just work too much with PHPUnit like @MarcelloDuarte said ;) But that why I know who write it :D

**Comment by robocoder** [comment]
iAgreeWithThePositionThatPsrDoesntApplyInTheContextOfADomainSpecificLanguageButAlsoSeeThePotentialConfusionSinceSpecsWrittenInPhpspecArePhpSoBreakingFromPsrConventionShouldReinforceTheIdeaThatSpecsAreWrittenInADslWhereDifferentRulesApply.

**Comment by luzat** [comment]
First, my personal opinion: I find both conventions about equally readable. Tools can still choose to display output formatted in a different way (e.g. lower-case and separated by spaces). Following PSR-\* in specs would be a great thing mostly for automated inspections which I do consider useful for specs, too. It's enough work configuring exceptions for different code in the tools right now, if they support that at all.

If the spec (code) itself, where most of the DSL goes, will look horrible when following PSR one might refrain from trying to reach that goal. I don't think it's worth sacrificing conformity for a just slightly different function declaration alone, though, with a convention which is on a large part based on personal preference.

**Comment by docteurklein** [comment]
If php allows a few shotrcuts to make specs more readable, we should use them IMHO.

**Comment by MarcelloDuarte** [comment]
@henrikbjorn you are OK to have method_like_that but not with omitting visibility? Consider this: there will be other things phpspec will rely on (magic/reflective or not), that are features of PHP today, that will not work should the community decide to break BC.

Adding the public, out of fear it will break in future PHP versions is not good enough reason. I hope you agree with me there. I can see this coming from your zealousness as a good developer who wants to honor the standards. I've been there too. Our prime motivation is providing with a tool optimised to write specs. Specs are in a different category to code, just like config and templates. Our library (phpspec) follow PSR, our specs don't.

**Comment by everzet** [comment]
> @l3l0: Funny is that for me second @everzet example is more readable... matter of habits probably.
> 
> @luzat: I find both conventions about equally readable.

How? How can you easily read this: `itShouldPresentOnlyFirstLineOfMultilineString` and even find it readable??? I'm asking you, guys, cuz... well... i simply **can't** :)

Here's how i read those 2 examples naturally:

``` php
class StringPresenter extends ObjectBehavior
{
    function it_should_present_only_first_line_of_multiline_string()
    {
        $this->presentValue("some\nmultiline\nvalue")->shouldReturn('"some"...');
    }
```

`StringPresenter` has **function** - _it should present only first line of multiline string_

VS

``` php
class StringPresenter extends ObjectBehavior
{
    public function itShouldPresentOnlyFirstLineOfMultilineString()
    {
        $this->presentValue("some\nmultiline\nvalue")->shouldReturn('"some"...');
    }
```

`StringPresenter` has **public function** - _it should present da derp dee derp da teetley derpee derpee dumb_

Say both sentences out loud and ask yourself (or even better - your wife or grandma) - "what am i talking about?". **"public function"**?

This `public` keyword doesn't look like it makes lot of difference, but it does. It forces your mind to think in implementation, not behaviour details.

This `itShouldPresentOnlyFirstLineOfMultilineString` doesn't look too hard to read when it's alone in the spec. But what if you'll have tens of those? Running phpspec every time just to print output and to be able to read your examples? Sounds like a really bad and limiting idea to me...

**Comment by everzet** [comment]
And yeah, we're kinda crazy with @MarcelloDuarte about how good "code" (it's not really code, though IS php) sounds, looks and reads inside `spec/` folder. Because in our opinion, that's the primary goal of specification-enforcing tool - to make specs pronounceable, clean, readable and explicit.

**Comment by everzet** [comment]
@luzat what "automated inspections" you're talking about, btw?

**Comment by luzat** [comment]
@everzet, there really is not much of a readability difference to me. At least not one that matters. I do understand that others might feel differently. As for the tools, I was mainly thinking of PHP_CodeSniffer here.

Anyway, you don't get a strong vote for strictly following PSR-\* in specs either. I don't consider either direction invalid.

**Comment by everzet** [comment]
@luzat well, you can apply PHP_CodeSniffer only to specific folder. For specs, different checks should be applied - how readable/understandable/readable they are :)

**Comment by awildeep** [comment]
The problem I have with underscore syntax is not in readability, but I hate the keystroke required to type it.  But a lazy generator/snippet/editor will fix this is really a moot point.

As for spec method readability, I find both conventions a but awkward.  We've trained our brains to look for a space between words for readability, not capitals, not underscores.   However we have a _limitation_ in the language that stops us from using spaces in our method names.  I suspect that some individuals may actually see and interpret camelCase easier than underscore, and in some cases the opposite will be true. 

Personally I would love to see an automated CLI interaction for adding a spec method. Calling something like:

```
phpspec desc my/namespace/class 'It should also accept an optional method description.'
```

This would have a few side effects:
1. If users switch to CLI to add a method, it helps them separate coding from spec'ing.  (This is one of the benefits cited as a pro for underscore syntax)
2. It allows me to type my description as a readable sentence.
3. The CLI could take that string, and if the class does not exist, offer to make it.  If it does exist, offer to append the spec to the class for you.
4. This means that it could even add a comment that is truly human readable, and does not use camel OR underscore syntaxes.  And spec methods could be more verbose (eg; include 'public' or not) but it is no more work for the developer.   Just their spec grows a bit in byte size.

Given the example above the following code could be auto-inserted into the spec file:

``` php
    /**
     * spec: It should also accept an optional method description.
     */
    public function it_should_also_accept_an_optional_method_description () {
         //code
    }
```

Or, just as easily:

``` php

    /**
     * spec: It should also accept an optional method description.
     */
    function itShouldAlsoAcceptAnOptionalMethodDescription () {
         //code
    }
```

These are just my initial thoughts.  Personally as soon as I saw this tool I was thinking about adding more CLI options.   What do you all think?

**Comment by everzet** [comment]
@awildeep there's a problem in your solution (annotations, not generators). It's called duplication. Now you have 2 duplicate sources of same information (method name AND annotation), which means that now you need to take care of both, which means that eventually one of them will become outdated, which will cause reusability problems. It's already hard enough to speak in behavioral terms when you're writing php, but what you're proposing is doubling that work :) This is not something, that will make your life easier, trust me :)

Generators though is a good idea and we'll definitely think about it.

**Comment by awildeep** [comment]
@everzet I never claimed it was a solution, just an idea. :P  I agree that maintenance is an issue with the comment in my structure, but I was trying to figure out a way to handle the issue.

Once I get used to this paradigm (TDD/BDD) as a whole, I could see a generator Symfony 2 bundle that could handle something like the @bundle notation.  I am sure a ZF2 module could use stuff like that just as effectively.

But ultimately, a generator helps the initial function build issue and provides separation of concerns (while I work on specs I should be in spec mode, and while I work on code I should be in code mode).  However it does not ultimately help with editable readability in the long run.  It at least it gets rid of the "I do not want to type more keystrokes" argument.

**Comment by MarcelloDuarte** [comment]
I feel the same as @awildeep (don't like typing underscores, despite all time spent on ruby stuff). Something along the lines of $ bin/phpspec describe Acme/Markdown "should convert asterisks to list items"... would be nice (I think).

**Comment by awildeep** [comment]
@MarcelloDuarte I find it interesting that you naturally left the 'it' prefix off of your example.  Maybe that should be optional in a generator?

```
$ bin/phpspec describe Acme/Markdown "should convert asterisks to list items"
```

Versus

```
$ bin/phpspec describe Acme/Markdown "it should convert asterisks to list items"
```

**Comment by MarcelloDuarte** [comment]
a-ha! The **it** refers to Markdown :) We are describing **it**. It's all about language.

I am OK with making it optional though, to avoid `it_it_` :) coming up in the code. I am all for making learning the tool easier.

**Comment by everzet** [comment]
If we'd go with generators, i'd rather go with https://gist.github.com/cd9e70d298080ac45779#comments

**Comment by MarcelloDuarte** [comment]
@everzet Problem will be people trying to write it themselves, copying the generators output.

**Comment by awildeep** [comment]
@everzet

`&ensp;` as a space.  Interesting.  

The issues I see:
1. Manual editing/maintenance
2. Bug reports from users expected space to work.
3. Is `&ensp;` supported in PHP on purpose, or as a mistake?
4. Code highlighters will not appreciate the syntax.  (Textmate hates it in my current build, but that may be fixable).

**Comment by everzet** [comment]
@MarcelloDuarte that's why they should be optional and disabled by default. People should know what they're doing.

**Comment by everzet** [comment]
Nah, after stating this, "people knowing what they're doing" sounds like a crazy idea even to myself :D

**Comment by awildeep** [comment]
@everzet "Nah, after stating this, people knowing what they're doing sounds like a crazy idea even to myself :D"  That quote made my day.

**Comment by MarcelloDuarte** [comment]
That's because it is crazy... but awesome. I am sure we will find a place for this.

**Comment by everzet** [comment]
@awildeep php doesn't care about most utf8 symbols since the beginning.

**Comment by MarcelloDuarte** [comment]
@awildeep I will open an issue. Are you up to claiming it?

**Comment by awildeep** [comment]
@MarcelloDuarte I am certainly willing to give it a shot.  Once you get an issue, can you link it here?  That way this conversation can continue as a discussion about syntax standards, but the generator issue an be pulled out and use this as a reference.

**Comment by MarcelloDuarte** [comment]
@awildeep #28

**Comment by everzet** [comment]
I'm closing this PR :)

**Pull request closed without merging**
