### PR TITLE
Codecoverage

### PR DESCRIPTION
**Pull request by henrikbjorn**
Currently this is hardcoded in the run command as it is not possible to do it through Events (there is not enough information available).

### CODE REVIEW

**Comment by everzet** [comment]
1. What information you need in events in order to make it a listener?
2. This shouldn't be in core (because of [that](https://github.com/Behat/Behat/issues/92#issuecomment-5620394)), though it's ok to have this as extension in the future (extension system is coming)

**Comment by MarcelloDuarte** [comment]
@henrikbjorn my thoughts on code coverage: http://bit.ly/mdcoverage

Having said that I wouldn't mind having the feature: it doesn't affects performance, it was added cleanly and I do get tired of repeating myself trying to educate people on this. What others think?

**Comment by henrikbjorn** [comment]
Everzet would need access to what parameters that have been set. Would need access to io if it should print messages.

@MarcelloDuarte On stackoverflow you use the word "properly". I would thing it is a good indicator for seeing the general status for tests. Do we actually cover stuff with tests? etc. It is a utility tool not something that is used frequently.

Running it on PHPSpec2 it self there is a lot of untested code (as there is also no unit tests).

**Comment by MarcelloDuarte** [comment]
@henrikbjorn yeah I use "properly" to indicate **what really matters**. In truth when you TDD, not all your code is covered. And it doesn't really matter, because we are not focusing on verification, we are not verifying that our classes work. The fact we get that is a nice side effect, a by-product. TDD give us a short feedback cycle, reducing big design tasks into many manageable small design decisions.

Many spec (tests) will hit the same line of code, if you code is properly refactored. If you use code coverage to make sure it is tested, you will probably write one or two tests. In addition there will be code without tests (don't do this in front of the children!), if you are experienced with the process. **phpspec** is a tool, the technique is there to serve you and not the other way around. A lot of aberrations emerge from the verification focus.

Code coverage will only guarantee the code works from the perspective of the test you wrote, if the test is added one week after you wrote the code, chances are it is not from the perspective of the expected behaviour. It's definitely not coming from a design decision. So code coverage is not even a good indicator. it's a poor metric at best.

I can see a TDD/Emergent design tool like **phpspec** being used for legacy code. But I wouldn't be too bothered myself about code coverage. I don't want to cover code I will probably delete after refactoring.

But like I said I am OK with having the feature for those who see any value in this. Can you wait for extension points, like @everzet suggests?

**Comment by everzet** [comment]
And as of "lot of untested code in phpspec". As @MarcelloDuarte said, plan was not to test, but to drive design by specs. Problem is, some core things of phpspec just couldn't be described with phpspec, because it'll constantly try to unwrap collaborator wrappers and do other nasty things. There were 2 choices for us - add dirty workarounds just to make phpspec speccable with itself OR cover just what we can cover. We've chosen second, as it was better design decision. We're avoiding specs sometimes because of our experience, but just to make sure that you'll not need to do the same in other projects ;)

**Comment by henrikbjorn** [comment]
Closing as this can be implemented as an extension using an event listener quite easily. preprepre prototype https://gist.github.com/4031055

**Pull request closed without merging**
