### PR TITLE
[WIP] Extensions subsystem

### PR DESCRIPTION
**Pull request by everzet**
Base implementation of extension system.

Where to look at:
- [Initializers](https://github.com/phpspec/phpspec2/tree/feature/extensions/src/PHPSpec2/Initializer)

### CODE REVIEW

**Comment by MarcelloDuarte** [comment]
Can you please write a short README/wiki entry on how to use these initializers? I am working on a extension to use with Magento projects. I am not sure how to use the initializers there.

**Comment by everzet** [comment]
No way for now. It's **WIP**

**Comment by MarcelloDuarte** [comment]
What's the value of merging a (this) WIP PR?

**Comment by everzet** [comment]
No value at all. That's why it shouldn't be merged yet.

**Pull request merged**
